### ISSUE TITLE
Unit test FAIL: testSentencepieceTokenizer (test.unit.test_tokenizer.TestTokenizer)

### ISSUE THREAD

**Issue by jeiea** [joeynmt/joeynmt#205] opened 2023-02-07 21:40 UTC
**Describe the bug**
I can't make unit test pass due to the error `(FAIL: testSentencepieceTokenizer (test.unit.test_tokenizer.TestTokenizer)`.

**To Reproduce**
1. I followed [documentation installation steps](https://joeynmt.readthedocs.io/en/latest/install.html).
2. configuration file [e.g. my_config.yaml] -> what's the configuration file?
3. commands
```
> py -3.9 -m venv jnmt
> &.\jnmt\Scripts\Activate.ps1
> pip install .
```

**Actual behavior**
<details>
<summary>
Outputs
</summary>

```
> pip install .
Processing joeynmt
  Preparing metadata (setup.py) ... done
Requirement already satisfied: future in joeynmt\jnmt\lib\site-packages (from joeynmt==2.2.0) (0.18.3)
Requirement already satisfied: pillow in joeynmt\jnmt\lib\site-packages (from joeynmt==2.2.0) (9.4.0)
Requirement already satisfied: numpy>=1.19.5 in joeynmt\jnmt\lib\site-packages (from joeynmt==2.2.0) (1.24.2)
Requirement already satisfied: setuptools>=41.0.0 in joeynmt\jnmt\lib\site-packages (from joeynmt==2.2.0) (58.1.0)
Requirement already satisfied: torch>=1.12.0 in joeynmt\jnmt\lib\site-packages (from joeynmt==2.2.0) (1.13.1)
Requirement already satisfied: protobuf<3.21,>=3.19.4 in joeynmt\jnmt\lib\site-packages (from joeynmt==2.2.0) (3.20.3)
Requirement already satisfied: tensorboard>=1.15 in joeynmt\jnmt\lib\site-packages (from joeynmt==2.2.0) (2.11.2)
Requirement already satisfied: sacrebleu>=2.0.0 in joeynmt\jnmt\lib\site-packages (from joeynmt==2.2.0) (2.3.1)
Requirement already satisfied: sentencepiece in joeynmt\jnmt\lib\site-packages (from joeynmt==2.2.0) (0.1.97)
Requirement already satisfied: subword-nmt in joeynmt\jnmt\lib\site-packages (from joeynmt==2.2.0) (0.3.8)
Requirement already satisfied: matplotlib in joeynmt\jnmt\lib\site-packages (from joeynmt==2.2.0) (3.6.3)
Requirement already satisfied: seaborn in joeynmt\jnmt\lib\site-packages (from joeynmt==2.2.0) (0.12.2)
Requirement already satisfied: pyyaml>=5.1 in joeynmt\jnmt\lib\site-packages (from joeynmt==2.2.0) (6.0)
Requirement already satisfied: six>=1.12 in joeynmt\jnmt\lib\site-packages (from joeynmt==2.2.0) (1.16.0)
Requirement already satisfied: wrapt>=1.11.1 in joeynmt\jnmt\lib\site-packages (from joeynmt==2.2.0) (1.14.1)
Requirement already satisfied: pylint in joeynmt\jnmt\lib\site-packages (from joeynmt==2.2.0) (2.16.1)
Requirement already satisfied: yapf in joeynmt\jnmt\lib\site-packages (from joeynmt==2.2.0) (0.32.0)
Requirement already satisfied: flake8 in joeynmt\jnmt\lib\site-packages (from joeynmt==2.2.0) (6.0.0)
Requirement already satisfied: pytest in joeynmt\jnmt\lib\site-packages (from joeynmt==2.2.0) (7.2.1)
Requirement already satisfied: datasets in joeynmt\jnmt\lib\site-packages (from joeynmt==2.2.0) (2.9.0)
Requirement already satisfied: packaging in joeynmt\jnmt\lib\site-packages (from joeynmt==2.2.0) (23.0)
Requirement already satisfied: lxml in joeynmt\jnmt\lib\site-packages (from sacrebleu>=2.0.0->joeynmt==2.2.0) (4.9.2)
Requirement already satisfied: regex in joeynmt\jnmt\lib\site-packages (from sacrebleu>=2.0.0->joeynmt==2.2.0) (2022.10.31)
Requirement already satisfied: portalocker in joeynmt\jnmt\lib\site-packages (from sacrebleu>=2.0.0->joeynmt==2.2.0) (2.7.0)
Requirement already satisfied: tabulate>=0.8.9 in joeynmt\jnmt\lib\site-packages (from sacrebleu>=2.0.0->joeynmt==2.2.0) (0.9.0)
Requirement already satisfied: colorama in joeynmt\jnmt\lib\site-packages (from sacrebleu>=2.0.0->joeynmt==2.2.0) (0.4.6)
Requirement already satisfied: werkzeug>=1.0.1 in joeynmt\jnmt\lib\site-packages (from tensorboard>=1.15->joeynmt==2.2.0) (2.2.2)
Requirement already satisfied: grpcio>=1.24.3 in joeynmt\jnmt\lib\site-packages (from tensorboard>=1.15->joeynmt==2.2.0) (1.51.1)
Requirement already satisfied: tensorboard-data-server<0.7.0,>=0.6.0 in joeynmt\jnmt\lib\site-packages (from tensorboard>=1.15->joeynmt==2.2.0) (0.6.1)
Requirement already satisfied: google-auth<3,>=1.6.3 in joeynmt\jnmt\lib\site-packages (from tensorboard>=1.15->joeynmt==2.2.0) (2.16.0)
Requirement already satisfied: requests<3,>=2.21.0 in joeynmt\jnmt\lib\site-packages (from tensorboard>=1.15->joeynmt==2.2.0) (2.28.2)
Requirement already satisfied: markdown>=2.6.8 in joeynmt\jnmt\lib\site-packages (from tensorboard>=1.15->joeynmt==2.2.0) (3.4.1)
Requirement already satisfied: absl-py>=0.4 in joeynmt\jnmt\lib\site-packages (from tensorboard>=1.15->joeynmt==2.2.0) (1.4.0)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in joeynmt\jnmt\lib\site-packages (from tensorboard>=1.15->joeynmt==2.2.0) (1.8.1)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in joeynmt\jnmt\lib\site-packages (from tensorboard>=1.15->joeynmt==2.2.0) (0.4.6)
Requirement already satisfied: wheel>=0.26 in joeynmt\jnmt\lib\site-packages (from tensorboard>=1.15->joeynmt==2.2.0) (0.38.4)
Requirement already satisfied: typing-extensions in joeynmt\jnmt\lib\site-packages (from torch>=1.12.0->joeynmt==2.2.0) (4.4.0)
Requirement already satisfied: dill<0.3.7 in joeynmt\jnmt\lib\site-packages (from datasets->joeynmt==2.2.0) (0.3.6)
Requirement already satisfied: tqdm>=4.62.1 in joeynmt\jnmt\lib\site-packages (from datasets->joeynmt==2.2.0) (4.64.1)
Requirement already satisfied: fsspec[http]>=2021.11.1 in joeynmt\jnmt\lib\site-packages (from datasets->joeynmt==2.2.0) (2023.1.0)
Requirement already satisfied: multiprocess in joeynmt\jnmt\lib\site-packages (from datasets->joeynmt==2.2.0) (0.70.14)
Requirement already satisfied: aiohttp in joeynmt\jnmt\lib\site-packages (from datasets->joeynmt==2.2.0) (3.8.3)
Requirement already satisfied: pandas in joeynmt\jnmt\lib\site-packages (from datasets->joeynmt==2.2.0) (1.5.3)
Requirement already satisfied: huggingface-hub<1.0.0,>=0.2.0 in joeynmt\jnmt\lib\site-packages (from datasets->joeynmt==2.2.0) (0.12.0)
Requirement already satisfied: responses<0.19 in joeynmt\jnmt\lib\site-packages (from datasets->joeynmt==2.2.0) (0.18.0)
Requirement already satisfied: xxhash in joeynmt\jnmt\lib\site-packages (from datasets->joeynmt==2.2.0) (3.2.0)
Requirement already satisfied: pyarrow>=6.0.0 in joeynmt\jnmt\lib\site-packages (from datasets->joeynmt==2.2.0) (11.0.0)
Requirement already satisfied: mccabe<0.8.0,>=0.7.0 in joeynmt\jnmt\lib\site-packages (from flake8->joeynmt==2.2.0) (0.7.0)
Requirement already satisfied: pycodestyle<2.11.0,>=2.10.0 in joeynmt\jnmt\lib\site-packages (from flake8->joeynmt==2.2.0) (2.10.0)
Requirement already satisfied: pyflakes<3.1.0,>=3.0.0 in joeynmt\jnmt\lib\site-packages (from flake8->joeynmt==2.2.0) (3.0.1)
Requirement already satisfied: fonttools>=4.22.0 in joeynmt\jnmt\lib\site-packages (from matplotlib->joeynmt==2.2.0) (4.38.0)
Requirement already satisfied: kiwisolver>=1.0.1 in joeynmt\jnmt\lib\site-packages (from matplotlib->joeynmt==2.2.0) (1.4.4)
Requirement already satisfied: cycler>=0.10 in joeynmt\jnmt\lib\site-packages (from matplotlib->joeynmt==2.2.0) (0.11.0)
Requirement already satisfied: python-dateutil>=2.7 in joeynmt\jnmt\lib\site-packages (from matplotlib->joeynmt==2.2.0) (2.8.2)
Requirement already satisfied: pyparsing>=2.2.1 in joeynmt\jnmt\lib\site-packages (from matplotlib->joeynmt==2.2.0) (3.0.9)
Requirement already satisfied: contourpy>=1.0.1 in joeynmt\jnmt\lib\site-packages (from matplotlib->joeynmt==2.2.0) (1.0.7)
Requirement already satisfied: tomli>=1.1.0 in joeynmt\jnmt\lib\site-packages (from pylint->joeynmt==2.2.0) (2.0.1)
Requirement already satisfied: platformdirs>=2.2.0 in joeynmt\jnmt\lib\site-packages (from pylint->joeynmt==2.2.0) (3.0.0)
Requirement already satisfied: tomlkit>=0.10.1 in joeynmt\jnmt\lib\site-packages (from pylint->joeynmt==2.2.0) (0.11.6)
Requirement already satisfied: astroid<=2.16.0-dev0,>=2.14.1 in joeynmt\jnmt\lib\site-packages (from pylint->joeynmt==2.2.0) (2.14.1)
Requirement already satisfied: isort<6,>=4.2.5 in joeynmt\jnmt\lib\site-packages (from pylint->joeynmt==2.2.0) (5.12.0)
Requirement already satisfied: pluggy<2.0,>=0.12 in joeynmt\jnmt\lib\site-packages (from pytest->joeynmt==2.2.0) (1.0.0)
Requirement already satisfied: iniconfig in joeynmt\jnmt\lib\site-packages (from pytest->joeynmt==2.2.0) (2.0.0)
Requirement already satisfied: attrs>=19.2.0 in joeynmt\jnmt\lib\site-packages (from pytest->joeynmt==2.2.0) (22.2.0)
Requirement already satisfied: exceptiongroup>=1.0.0rc8 in joeynmt\jnmt\lib\site-packages (from pytest->joeynmt==2.2.0) (1.1.0)
Requirement already satisfied: mock in joeynmt\jnmt\lib\site-packages (from subword-nmt->joeynmt==2.2.0) (5.0.1)
Requirement already satisfied: lazy-object-proxy>=1.4.0 in joeynmt\jnmt\lib\site-packages (from astroid<=2.16.0-dev0,>=2.14.1->pylint->joeynmt==2.2.0) (1.9.0)
Requirement already satisfied: yarl<2.0,>=1.0 in joeynmt\jnmt\lib\site-packages (from aiohttp->datasets->joeynmt==2.2.0) (1.8.2)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in joeynmt\jnmt\lib\site-packages (from aiohttp->datasets->joeynmt==2.2.0) (4.0.2)
Requirement already satisfied: frozenlist>=1.1.1 in joeynmt\jnmt\lib\site-packages (from aiohttp->datasets->joeynmt==2.2.0) (1.3.3)
Requirement already satisfied: aiosignal>=1.1.2 in joeynmt\jnmt\lib\site-packages (from aiohttp->datasets->joeynmt==2.2.0) (1.3.1)
Requirement already satisfied: multidict<7.0,>=4.5 in joeynmt\jnmt\lib\site-packages (from aiohttp->datasets->joeynmt==2.2.0) (6.0.4)
Requirement already satisfied: charset-normalizer<3.0,>=2.0 in joeynmt\jnmt\lib\site-packages (from aiohttp->datasets->joeynmt==2.2.0) (2.1.1)
Requirement already satisfied: pyasn1-modules>=0.2.1 in joeynmt\jnmt\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard>=1.15->joeynmt==2.2.0) (0.2.8)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in joeynmt\jnmt\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard>=1.15->joeynmt==2.2.0) (5.3.0)
Requirement already satisfied: rsa<5,>=3.1.4 in joeynmt\jnmt\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard>=1.15->joeynmt==2.2.0) (4.9)
Requirement already satisfied: requests-oauthlib>=0.7.0 in joeynmt\jnmt\lib\site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard>=1.15->joeynmt==2.2.0) (1.3.1)
Requirement already satisfied: filelock in joeynmt\jnmt\lib\site-packages (from huggingface-hub<1.0.0,>=0.2.0->datasets->joeynmt==2.2.0) (3.9.0)
Requirement already satisfied: importlib-metadata>=4.4 in joeynmt\jnmt\lib\site-packages (from markdown>=2.6.8->tensorboard>=1.15->joeynmt==2.2.0) (6.0.0)
Requirement already satisfied: pytz>=2020.1 in joeynmt\jnmt\lib\site-packages (from pandas->datasets->joeynmt==2.2.0) (2022.7.1)
Requirement already satisfied: idna<4,>=2.5 in joeynmt\jnmt\lib\site-packages (from requests<3,>=2.21.0->tensorboard>=1.15->joeynmt==2.2.0) (3.4)
Requirement already satisfied: certifi>=2017.4.17 in joeynmt\jnmt\lib\site-packages (from requests<3,>=2.21.0->tensorboard>=1.15->joeynmt==2.2.0) (2022.12.7)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in joeynmt\jnmt\lib\site-packages (from requests<3,>=2.21.0->tensorboard>=1.15->joeynmt==2.2.0) (1.26.14)
Requirement already satisfied: MarkupSafe>=2.1.1 in joeynmt\jnmt\lib\site-packages (from werkzeug>=1.0.1->tensorboard>=1.15->joeynmt==2.2.0) (2.1.2)
Requirement already satisfied: pywin32>=226 in joeynmt\jnmt\lib\site-packages (from portalocker->sacrebleu>=2.0.0->joeynmt==2.2.0) (305)
Requirement already satisfied: zipp>=0.5 in joeynmt\jnmt\lib\site-packages (from importlib-metadata>=4.4->markdown>=2.6.8->tensorboard>=1.15->joeynmt==2.2.0) (3.12.1)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in joeynmt\jnmt\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard>=1.15->joeynmt==2.2.0) (0.4.8)
Requirement already satisfied: oauthlib>=3.0.0 in joeynmt\jnmt\lib\site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard>=1.15->joeynmt==2.2.0) (3.2.2)
Building wheels for collected packages: joeynmt
  Building wheel for joeynmt (setup.py) ... done
  Created wheel for joeynmt: filename=joeynmt-2.2.0-py3-none-any.whl size=112988 sha256=1cfa0739e55075f3dcf6c8b71eb6f4a7f838e0b55537617fdebc40b4890ac74c
  Stored in directory: C:\Users\jeiea\AppData\Local\Temp\pip-ephem-wheel-cache-skctw138\wheels\db\66\94\766fe26114a3d248180b82dfe0929a236a5038ea6d15eb8996
Successfully built joeynmt
Installing collected packages: joeynmt
  Attempting uninstall: joeynmt
    Found existing installation: joeynmt 2.2.0
    Uninstalling joeynmt-2.2.0:
      Successfully uninstalled joeynmt-2.2.0
Successfully installed joeynmt-2.2.0
WARNING: You are using pip version 22.0.4; however, version 23.0 is available.
You should consider upgrading via the 'joeynmt\jnmt\Scripts\python.exe -m pip install --upgrade pip' command.

> py -m unittest     
Predicting...: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:00<00:00, 52.09it/s]
Predicting...: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:00<00:00, 52.31it/s] 
............Fjoeynmt\joeynmt\tokenizers.py:347: ResourceWarning: unclosed file <_io.TextIOWrapper name='test/data/toy/bpe200.codes' mode='r' encoding='cp949'>
  tokenizer = SubwordNMTTokenizer(
ResourceWarning: Enable tracemalloc to get the object allocation traceback
..................
======================================================================
FAIL: testSentencepieceTokenizer (test.unit.test_tokenizer.TestTokenizer)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "joeynmt\test\unit\test_tokenizer.py", line 158, in testSentencepieceTokenizer
    self.assertEqual(dropout, expected[lang]['dropout'])
AssertionError: Lists differ: ['▁D'[40 chars]', 'i', 'l', '▁der', '▁E', 'r', 'd', 'e', '▁is[42 chars] '.'] != ['▁D'[40 chars]', 'il', '▁der', '▁E', 'r', 'd', 'e', '▁ist', [42 chars] '.']

First differing element 9:
'i'
'il'

  ['▁D',
   'er',
   '▁',
   'G',
   'r',
   'o',
   'ß',
   't',
   'e',
-  'i',
+  'il',
?    +

-  'l',
   '▁der',
   '▁E',
   'r',
   'd',
   'e',
   '▁ist',
   '▁M',
   'e',
   'er',
   'w',
-  'as',
?    -

+  'a',
   's',
+  'se',
-  'er',
?   -

+  'r',
   '.']

----------------------------------------------------------------------
Ran 73 tests in 2.944s

FAILED (failures=1, skipped=1)
```
</details>

**Expected behavior**
Test pass

**System:**
 - OS: Microsoft Windows 11 Pro 10.0.22621 N/A Build 22621 x64
 - CPU / GPU: AMD64 Family 25 Model 33 Stepping 0 AuthenticAMD ~3701 Mhz / NVIDIA GeForce RTX 3070
 - Python Version: 3.9.13

**Additional context**
Can I ignore this?

**Comment by may-** [comment] 2023-02-11 22:17
Hi @jeiea, 

Could you please try to rewrite the following line in `joeynmt/tokenizers.py`:
https://github.com/joeynmt/joeynmt/blob/4df0e7dc46393cbee0ca4160f4c49798874f15cb/joeynmt/tokenizers.py#L176-L180
to
```python
        tokenized = self.spm.SampleEncodeAsPieces(
            raw_input,
            nbest_size=self.nbest_size,
            alpha=self.alpha,
        )
```
And please rerun the unittests. Does the test pass??
In my Linux environment, both syntax works. But I guess there are some OS-specific issues in encoding, maybe... I'm not sure though.


BTW, you can ignore the error if you don't use sentencepiece tokenizer in your experiments. However, some encoding problem might occur somewhere even without sentencepiece...

**Comment by jeiea** [comment] 2023-02-12 12:18
Still same. `test/data/toy/bpe200.codes` also has utf-8 encoding. I checked it by vscode status line.

**Comment by may-** [comment] 2023-02-12 14:44
Hum, ok, presumably, we cannot set a random seed in sampling to reproduce the same tokenization.
I observe a different sampling everytime I call the encode func.
I'll remove the bpe dropout from the sentencepiece unittest.

Thank you for catching this error!
Basically, it's not a bug, but a mis-conception in our unittest design, I'd say.

cf. https://github.com/google/sentencepiece/issues/609

**Comment by may-** [comment] 2023-02-12 19:22
@jeiea 
I merged the unittest fix. Please pull the latest main repo :)

**Closed** 2023-03-12 14:45 UTC
