### ISSUE TITLE
joeynmt/scripts/build_vocab.py error

### ISSUE THREAD

**Issue by KashyapKishore** [joeynmt/joeynmt#179] opened 2022-06-04 15:24 UTC
In the build_vocab.py, the developer has omitted the '#!/usr/bin/env python' at the top of the file and as a result the following error is occurring :

joeynmt/scripts/build_vocab.py: line 3: import: command not found
joeynmt/scripts/build_vocab.py: line 4: import: command not found
joeynmt/scripts/build_vocab.py: line 5: import: command not found
.........

Please rectify it. When I locally inserted the line, it ran smoothly.

But, now another error related to usage is showing up. What changes are made to command line argument passing to build_vocab.py ?
Please look into it.

**Comment by may-** [comment] 2022-06-04 17:39
Hi,

Could you please give us your error log? The current version of `build_vocab.py` takes one required positional argument (config.yaml path), and three optional keyword arguments (--join, --random-subset, and --seed).

Have you created any virtual env for joeynmt? like venv or conda? What is the return value of `which python` command?

**Comment by juliakreutzer** [comment] 2022-06-04 18:32
Thanks @KashyapKishore! `build_vocab` has changed a lot with v2.0. As @may- described, you now pass it the config directly as argument, and it will read the data paths and tokenizer configurations directly from there, and also train your subword model (if specified in the configuration). This should eventually simplify your workflow. 

@may- does anything speak against adding the `#!/usr/bin/env python`? We have it for the other scripts as well.

**Comment by may-** [comment] 2022-06-04 18:36
@juliakreutzer As far as I understand, `#!/usr/bin/env python` enables the script call without `python` command, like
```
$ ./scripts/build_vocab.py config.yaml
``` 
Do we want to allow this? Then yes. I personally prefer to call the script explicitly with the python command, but it's just my personal preference...

**Comment by juliakreutzer** [comment] 2022-06-04 18:54
Yes, that's what it does. Since we have it for the other scripts as well, I think doesn't hurt to add it.

**Comment by may-** [comment] 2022-06-04 18:58
ok, then let's do that :)

**Comment by KashyapKishore** [comment] 2022-06-04 19:28
Thank you @juliakreutzer @may-. We are running our experiment in Google Colab Pro environment due to some local hardware issues we are currently facing. I have checked, without the shebang line, the file shows error like I have mentioned 'import: command not found'. OK, once the line is added, it works fine.

Now another issue we are getting is, when we tried incorporating the changes and supplied the config file, we are getting error like:
Traceback (most recent call last):
  File "joeynmt/scripts/build_vocab.py", line 342, in <module>
    main(args)
  File "joeynmt/scripts/build_vocab.py", line 248, in main
    src_cfg["lang"]:
TypeError: string indices must be integers


Can you please check ?

**Comment by may-** [comment] 2022-06-04 20:30
which config file do you mean?

**Comment by KashyapKishore** [comment] 2022-06-05 07:38
Thanks @may- @juliakreutzer We have used the config file $trg$src-transformer.yml file as the config file. Is it OK?
OR
Can you provide some quick tutorial to work with ver 2.0 of JoeyNMT?

**Comment by KashyapKishore** [comment] 2022-06-05 07:42
Thanks @may- @juliakreutzer We have used the config file $trg$src-transformer.yml file as the config file. Is it OK?

**Comment by may-** [comment] 2022-06-05 08:23
Hi @KashyapKishore,
for plaintext (one sentence per line) data, I've confirmed `build_vocab.py` worked with these iwslt14 config files:
- (subword-nmt) https://github.com/joeynmt/joeynmt/blob/main/configs/iwslt14_deen_bpe.yaml
- (sentencepiece) https://github.com/joeynmt/joeynmt/blob/main/configs/iwslt14_deen_sp.yaml

[transformer_small.yaml](https://github.com/may-/joeynmt/blob/main/configs/transformer_small.yaml) has detailed explanation for each option.

I pushed a quick start tutorial [here](https://github.com/may-/joeynmt/blob/py37/notebooks/quick-start-with-joeynmt2.ipynb) (compatible with Google Colab environment). I hope it helps.

**Comment by KashyapKishore** [comment] 2022-06-05 09:09
@may- Thanks a lot. Currently we have downgraded to ver 1.3 of joeyNMT and training is going on. With your above guidelnes, we are starting to experiment with V2.0 now. Our language pair is English-Assamese (en-as).

Thank you 👍

**Comment by may-** [comment] 2022-08-24 19:42
I close this for now. See https://github.com/joeynmt/joeynmt/pull/181. Please reopen it if you still have the problem.

**Closed by may-** 2022-08-24 19:42 UTC
